var annotated_dup =
[
    [ "Board", "classBoard.html", "classBoard" ],
    [ "Client", "classClient.html", "classClient" ],
    [ "ClientSession", "structClientSession.html", "structClientSession" ],
    [ "CLIInterface", "classCLIInterface.html", "classCLIInterface" ],
    [ "Connection", "classConnection.html", "classConnection" ],
    [ "ConnectRequest", "structConnectRequest.html", "structConnectRequest" ],
    [ "ConnectResponse", "structConnectResponse.html", "structConnectResponse" ],
    [ "CreateGameRequest", "structCreateGameRequest.html", "structCreateGameRequest" ],
    [ "CreateGameResponse", "structCreateGameResponse.html", "structCreateGameResponse" ],
    [ "DisconnectMessage", "structDisconnectMessage.html", "structDisconnectMessage" ],
    [ "ErrorMessage", "structErrorMessage.html", "structErrorMessage" ],
    [ "GameConfig", "structGameConfig.html", "structGameConfig" ],
    [ "GameEngine", "classGameEngine.html", "classGameEngine" ],
    [ "GameInfo", "structGameInfo.html", "structGameInfo" ],
    [ "GameOverMessage", "structGameOverMessage.html", "structGameOverMessage" ],
    [ "GameRules", "classGameRules.html", "classGameRules" ],
    [ "GameServer", "classGameServer.html", "classGameServer" ],
    [ "GameSession", "classGameSession.html", "classGameSession" ],
    [ "GameSpec", "structGameSpec.html", "structGameSpec" ],
    [ "GameState", "classGameState.html", "classGameState" ],
    [ "GameStateUpdate", "structGameStateUpdate.html", "structGameStateUpdate" ],
    [ "HeartbeatMessage", "structHeartbeatMessage.html", "structHeartbeatMessage" ],
    [ "JoinGameRequest", "structJoinGameRequest.html", "structJoinGameRequest" ],
    [ "JoinGameResponse", "structJoinGameResponse.html", "structJoinGameResponse" ],
    [ "ListGamesRequest", "structListGamesRequest.html", "structListGamesRequest" ],
    [ "ListGamesResponse", "structListGamesResponse.html", "structListGamesResponse" ],
    [ "MakeMoveRequest", "structMakeMoveRequest.html", "structMakeMoveRequest" ],
    [ "MessageSerializer", "classMessageSerializer.html", null ],
    [ "Move", "structMove.html", "structMove" ],
    [ "MoveResult", "structMoveResult.html", "structMoveResult" ],
    [ "PlayerVisual", "structPlayerVisual.html", "structPlayerVisual" ],
    [ "SessionManager", "classSessionManager.html", "classSessionManager" ]
];